projects:
- {name: Bookshelf, folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: Podcast, folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: Autism Robot, folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: Random, folder: 'proj-4', file: 'projects/proj-4.html'}
